import { Roboto } from "next/font/google";
import "./globals.css";
import ClientProviders from "@/components/ClientProviders";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
  title: "E - Commerce Admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClientProviders>
      <html lang="en">
        <body className={roboto.className}>{children}</body>
      </html>
    </ClientProviders>
  );
}
